<?php
if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group([
        'key' => 'group_blog_page',
        'title' => 'Blog Page',
        'fields' => [
            // Header Section Group (for section-category-list.php)
            [
                'key' => 'field_header_group',
                'label' => 'Header Category Section',
                'name' => 'header_group',
                'type' => 'group',
                'instructions' => 'Fields for the header section of the blog page.',
                'required' => 0,
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_header_subtitle',
                        'label' => 'Header Subtitle',
                        'name' => 'category_subtitle',
                        'type' => 'text',
                        'instructions' => 'Enter the subtitle for the Header section (e.g., "Where I Can Help").',
                        'required' => 1,
                        'default_value' => 'Where I Can Help',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_header_title',
                        'label' => 'Header Title',
                        'name' => 'category_title',
                        'type' => 'text',
                        'instructions' => 'Enter the main title for the Header section (e.g., "Our Process").',
                        'required' => 1,
                        'default_value' => 'Our Process',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Trending Articles Section Group
            [
                'key' => 'field_trending_group',
                'label' => 'Trending Articles Section',
                'name' => 'trending_group',
                'type' => 'group',
                'instructions' => 'Fields for the Trending Articles section.',
                'required' => 0,
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_trending_subtitle_new',
                        'label' => 'Trending Articles Subtitle',
                        'name' => 'trending_subtitle',
                        'type' => 'text',
                        'instructions' => 'Enter the subtitle for the Trending Articles section (e.g., "Trending Articles").',
                        'required' => 1,
                        'default_value' => 'Trending Articles',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_trending_title_new',
                        'label' => 'Trending Articles Title',
                        'name' => 'trending_title',
                        'type' => 'text',
                        'instructions' => 'Enter the main title for the Trending Articles section (e.g., "Where Knowledge Meets Passion").',
                        'required' => 1,
                        'default_value' => 'Where Knowledge Meets Passion',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_trending_description',
                        'label' => 'Trending Articles Description',
                        'name' => 'trending_description',
                        'type' => 'textarea',
                        'instructions' => 'Enter the description for the Trending Articles section.',
                        'required' => 0,
                        'default_value' => 'Trending Articles of consectetur morbi. Amet venenatis urna cursus eget nunc scelerisque viverra.',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_trending_button_text',
                        'label' => 'Trending Articles Button Text',
                        'name' => 'trending_button_text',
                        'type' => 'text',
                        'instructions' => 'Enter the text for the All Posts button in the Trending Articles section (e.g., "All Posts").',
                        'required' => 1,
                        'default_value' => 'All Posts',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_trending_button_link',
                        'label' => 'Trending Articles Button Link',
                        'name' => 'trending_button_link',
                        'type' => 'link',
                        'instructions' => 'Select or enter the link for the All Posts button in the Trending Articles section.',
                        'required' => 1,
                        'return_format' => 'array',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Latest Articles Section Group
            [
                'key' => 'field_latest_group',
                'label' => 'Latest Articles Section',
                'name' => 'latest_group',
                'type' => 'group',
                'instructions' => 'Fields for the Latest Articles section.',
                'required' => 0,
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_latest_subtitle',
                        'label' => 'Latest Articles Subtitle',
                        'name' => 'latest_subtitle',
                        'type' => 'text',
                        'instructions' => 'Enter the subtitle for the Latest Articles section (e.g., "Latest Articles").',
                        'required' => 1,
                        'default_value' => 'Latest Articles',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_latest_title',
                        'label' => 'Latest Articles Title',
                        'name' => 'latest_title',
                        'type' => 'text',
                        'instructions' => 'Enter the main title for the Latest Articles section (e.g., "Discover. Learn. Transform. Quick").',
                        'required' => 1,
                        'default_value' => 'Discover. Learn. Transform. Quick',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_latest_description',
                        'label' => 'Latest Articles Description',
                        'name' => 'latest_description',
                        'type' => 'textarea',
                        'instructions' => 'Enter the description for the Latest Articles section.',
                        'required' => 0,
                        'default_value' => 'Latest Articles of Amet venenatis urna cursus eget nunc scelerisque viverra.',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_latest_button_text',
                        'label' => 'Latest Articles Button Text',
                        'name' => 'latest_button_text',
                        'type' => 'text',
                        'instructions' => 'Enter the text for the All Posts button in the Latest Articles section (e.g., "All Posts").',
                        'required' => 1,
                        'default_value' => 'All Posts',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_latest_button_link',
                        'label' => 'Latest Articles Button Link',
                        'name' => 'latest_button_link',
                        'type' => 'link',
                        'instructions' => 'Select or enter the link for the All Posts button in the Latest Articles section.',
                        'required' => 1,
                        'return_format' => 'array',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Popular Articles Section Group
            [
                'key' => 'field_popular_group',
                'label' => 'Popular Articles Section',
                'name' => 'popular_group',
                'type' => 'group',
                'instructions' => 'Fields for the Popular Articles section.',
                'required' => 0,
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_popular_subtitle',
                        'label' => 'Popular Articles Subtitle',
                        'name' => 'popular_subtitle',
                        'type' => 'text',
                        'instructions' => 'Enter the subtitle for the Popular Articles section (e.g., "Popular Articles").',
                        'required' => 1,
                        'default_value' => 'Popular Articles',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_popular_title',
                        'label' => 'Popular Articles Title',
                        'name' => 'popular_title',
                        'type' => 'text',
                        'instructions' => 'Enter the main title for the Popular Articles section (e.g., "Business insights and workplace culture").',
                        'required' => 1,
                        'default_value' => 'Business insights and workplace culture',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_popular_description',
                        'label' => 'Popular Articles Description',
                        'name' => 'popular_description',
                        'type' => 'textarea',
                        'instructions' => 'Enter the description for the Popular Articles section.',
                        'required' => 0,
                        'default_value' => 'Popular Articles of consectetur morbi. Amet venenatis urna cursus eget nunc scelerisque viverra.',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_popular_button_text',
                        'label' => 'Popular Articles Button Text',
                        'name' => 'popular_button_text',
                        'type' => 'text',
                        'instructions' => 'Enter the text for the All Posts button in the Popular Articles section (e.g., "All Posts").',
                        'required' => 1,
                        'default_value' => 'All Posts',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_popular_button_link',
                        'label' => 'Popular Articles Button Link',
                        'name' => 'popular_button_link',
                        'type' => 'link',
                        'instructions' => 'Select or enter the link for the All Posts button in the Popular Articles section.',
                        'required' => 1,
                        'return_format' => 'array',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
            // Post of the Week Section Group
            [
                'key' => 'field_post_of_the_week_group',
                'label' => 'Post of the Week Section',
                'name' => 'post_of_the_week_group',
                'type' => 'group',
                'instructions' => 'Fields for the Post of the Week section.',
                'required' => 0,
                'layout' => 'block',
                'sub_fields' => [
                    [
                        'key' => 'field_post_of_the_week_title',
                        'label' => 'Post of the Week Title',
                        'name' => 'post_of_the_week_title',
                        'type' => 'text',
                        'instructions' => 'Enter the title for the Post of the Week section (e.g., "Post of the Week").',
                        'required' => 1,
                        'default_value' => 'Post of the Week',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_post_of_the_week_button_text',
                        'label' => 'Post of the Week Button Text',
                        'name' => 'post_of_the_week_button_text',
                        'type' => 'text',
                        'instructions' => 'Enter the text for the All Weekly Posts button in the Post of the Week section (e.g., "All Weekly Posts").',
                        'required' => 1,
                        'default_value' => 'All Weekly Posts',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                    [
                        'key' => 'field_post_of_the_week_button_link',
                        'label' => 'Post of the Week Button Link',
                        'name' => 'post_of_the_week_button_link',
                        'type' => 'link',
                        'instructions' => 'Select or enter the link for the All Weekly Posts button in the Post of the Week section.',
                        'required' => 1,
                        'return_format' => 'array',
                        'wrapper' => [
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-blog.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'Fields for the sections on the blog page.',
    ]);
endif;
