<?php
if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
        'key' => 'group_seo_process_section',
        'title' => 'SEO Process Section',
        'fields' => array(
            array(
                'key' => 'field_section_title_top',
                'label' => 'Section Title Top',
                'name' => 'section_title_top',
                'type' => 'text',
                'instructions' => 'Enter an optional subtitle above the main section title.',
                'required' => 0,
                'default_value' => '',
                'placeholder' => 'Enter top subtitle',
                'maxlength' => 100,
            ),
            array(
                'key' => 'field_section_title',
                'label' => 'Section Title',
                'name' => 'section_title',
                'type' => 'text',
                'instructions' => 'Enter the main title for the SEO Process section.',
                'required' => 0,
                'default_value' => 'Our Process',
                'placeholder' => 'Enter section title',
                'maxlength' => 100,
            ),
            array(
                'key' => 'field_section_title_bottom',
                'label' => 'Section Title Bottom',
                'name' => 'section_title_bottom',
                'type' => 'text',
                'instructions' => 'Enter an optional subtitle below the main section title.',
                'required' => 0,
                'default_value' => '',
                'placeholder' => 'Enter bottom subtitle',
                'maxlength' => 200,
            ),
            array(
                'key' => 'field_seo_process_cubes',
                'label' => 'SEO Process Cubes',
                'name' => 'seo_process_cubes',
                'type' => 'repeater',
                'instructions' => 'Add cubes for the SEO Process section.',
                'required' => 0,
                'min' => 1,
                'max' => 10,
                'layout' => 'block',
                'button_label' => 'Add Cube',
                'sub_fields' => array(
                    array(
                        'key' => 'field_cube_title',
                        'label' => 'Cube Title',
                        'name' => 'cube_title',
                        'type' => 'text',
                        'instructions' => 'Enter the title for this cube.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'Enter cube title',
                        'maxlength' => 100,
                    ),
                    array(
                        'key' => 'field_cube_description',
                        'label' => 'Cube Description',
                        'name' => 'cube_description',
                        'type' => 'textarea',
                        'instructions' => 'Enter the description for this cube.',
                        'required' => 0,
                        'default_value' => '',
                        'placeholder' => 'Enter cube description',
                        'rows' => 4,
                        'maxlength' => 500,
                    ),
                    array(
                        'key' => 'field_cube_front_image',
                        'label' => 'Front Image',
                        'name' => 'cube_front_image',
                        'type' => 'image',
                        'instructions' => 'Upload the front image for the cube.',
                        'required' => 0,
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => 200,
                        'min_height' => 200,
                        'max_size' => 5,
                    ),
                    array(
                        'key' => 'field_cube_top_image',
                        'label' => 'Top Image',
                        'name' => 'cube_top_image',
                        'type' => 'image',
                        'instructions' => 'Upload the top image for the cube.',
                        'required' => 0,
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => 200,
                        'min_height' => 200,
                        'max_size' => 5,
                    ),
                ),
            ),
        ),
        'location' => array(
           
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-seo.php',
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-metaAds.php',
                ),
            ),
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-ppc.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'Fields for the SEO Process section on specific page templates.',
    ));
}
?>