<?php
if (function_exists('acf_add_local_field_group')) :
    acf_add_local_field_group([
        'key' => 'group_seo_hero_section',
        'title' => 'SEO Hero Section',
        'fields' => [
            [
                'key' => 'field_seo_hero_image_1',
                'label' => 'Hero Image 1',
                'name' => 'seo_hero_image_1',
                'type' => 'image',
                'instructions' => 'Upload the first hero image for the SEO page.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => 0,
                'min_height' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'mime_types' => 'jpg,jpeg,png,avif,webp',
            ],
            [
                'key' => 'field_seo_hero_image_2',
                'label' => 'Hero Image 2',
                'name' => 'seo_hero_image_2',
                'type' => 'image',
                'instructions' => 'Upload the second hero image for the SEO page.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => 0,
                'min_height' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'mime_types' => 'jpg,jpeg,png,avif,webp',
            ],
            [
                'key' => 'field_seo_hero_image_3',
                'label' => 'Hero Image 3',
                'name' => 'seo_hero_image_3',
                'type' => 'image',
                'instructions' => 'Upload the third hero image for the SEO page.',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => 0,
                'min_height' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'mime_types' => 'jpg,jpeg,png,avif,webp',
            ],
            [
                'key' => 'field_seo_hero_title',
                'label' => 'Hero Title',
                'name' => 'seo_hero_title',
                'type' => 'text',
                'instructions' => 'Enter the title for the SEO hero section.',
                'required' => 1,
                'default_value' => 'Mastering SEO Success',
                'placeholder' => 'Enter hero title',
                'maxlength' => '',
            ],
            [
                'key' => 'field_seo_hero_description',
                'label' => 'Hero Description',
                'name' => 'seo_hero_description',
                'type' => 'textarea',
                'instructions' => 'Enter the description for the SEO hero section.',
                'required' => 1,
                'default_value' => 'Boost your online presence with proven SEO strategies to rank higher and attract more traffic.',
                'placeholder' => 'Enter hero description',
                'rows' => 4,
                'new_lines' => 'wpautop',
            ],
            [
                'key' => 'field_seo_hero_cta_text_1',
                'label' => 'Primary CTA Button Text',
                'name' => 'seo_hero_cta_text_1',
                'type' => 'text',
                'instructions' => 'Enter the text for the primary CTA button.',
                'required' => 0,
                'default_value' => 'Get Started',
                'placeholder' => 'Enter primary CTA text',
                'maxlength' => '',
            ],
            [
                'key' => 'field_seo_hero_cta_link_1',
                'label' => 'Primary CTA Button Link',
                'name' => 'seo_hero_cta_link_1',
                'type' => 'url',
                'instructions' => 'Enter the URL for the primary CTA button.',
                'required' => 0,
                'default_value' => '#',
                'placeholder' => 'https://example.com',
            ],
            [
                'key' => 'field_seo_hero_cta_text_2',
                'label' => 'Secondary CTA Button Text',
                'name' => 'seo_hero_cta_text_2',
                'type' => 'text',
                'instructions' => 'Enter the text for the secondary CTA button.',
                'required' => 0,
                'default_value' => 'Learn More',
                'placeholder' => 'Enter secondary CTA text',
                'maxlength' => '',
            ],
            [
                'key' => 'field_seo_hero_cta_link_2',
                'label' => 'Secondary CTA Button Link',
                'name' => 'seo_hero_cta_link_2',
                'type' => 'url',
                'instructions' => 'Enter the URL for the secondary CTA button.',
                'required' => 0,
                'default_value' => '#',
                'placeholder' => 'https://example.com',
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-seo.php',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => 'Fields for the hero section on the SEO page.',
    ]);
endif;